### ISSUE TITLE
More specific error message, when the configuration data is invalid

### ISSUE THREAD

**Issue by cruizer** [cruizer/dup-composer#5]
This is too vague:
```
Traceback (most recent call last):
  File "./dupcomp.py", line 58, in <module>
    main()
  File "./dupcomp.py", line 34, in main
    config = BackupConfig(config_raw)
  File "/home/cruizer/Dev/python/dup-composer/dupcomposer/backup_config.py", line 26, in __init__
    self.createGroups()
  File "/home/cruizer/Dev/python/dup-composer/dupcomposer/backup_config.py", line 32, in createGroups
    self.groups.append(BackupGroup(groups_conf[group_name], group_name))
  File "/home/cruizer/Dev/python/dup-composer/dupcomposer/backup_config.py", line 52, in __init__
    raise KeyError('Invalid backup group configuration data')
KeyError: 'Invalid backup group configuration data'
```

**Comment by cruizer** [comment]
c752a022460f38d6905c5e796f3bde49868abdeb
